- name: "Generate client certificate key"
  become: yes
  shell: source vars; ./build-key --batch {{ item.client_name }}
  args: 
    chdir: "{{ ansible_env.HOME }}/openvpn-ca/"
    executable: /bin/bash
  loop: "{{ clients }}"

- name: "Create client certificate configs dir"
  become: yes
  file: 
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    path: "{{ ansible_env.HOME }}/client-configs"
    state: directory
    mode: 0700

- name: replace base file 
  template:
    src: ../templates/base.conf
    dest: "{{ ansible_env.HOME }}/client-configs/"
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: Set the server ip and port
  lineinfile:
    dest: "{{ ansible_env.HOME }}/client-configs/base.conf"
    regexp: "^{{ item.regex | regex_escape() }}"
    line: "{{ item.value }}"
  with_items:
    - { regex: 'remote my-server-1 1194', value: 'remote {{ groups["openVPN"][0] }} 1194' }

- name: Create a directory if it does not exist
  file:
    path: "{{ ansible_env.HOME }}/client-configs/files"
    state: directory
    mode: '0755'
  
- name: "Create client ovpn file"
  shell: |
    cat {{ ansible_env.HOME }}/client-configs/base.conf >> {{ ansible_env.HOME }}/client-configs/files/{{ item.client_name }}.ovpn
    echo  '<ca>' >> {{ ansible_env.HOME }}/client-configs/files/{{ item.client_name }}.ovpn
    cat {{ ansible_env.HOME }}/openvpn-ca/keys/ca.crt >> {{ ansible_env.HOME }}/client-configs/files/{{ item.client_name }}.ovpn
    echo  '</ca>\n<cert>' >> {{ ansible_env.HOME }}/client-configs/files/{{ item.client_name }}.ovpn
    cat {{ ansible_env.HOME }}/openvpn-ca/keys/{{ item.client_name }}.crt >> {{ ansible_env.HOME }}/client-configs/files/{{ item.client_name }}.ovpn
    echo  '</cert>\n<key>' >> {{ ansible_env.HOME }}/client-configs/files/{{ item.client_name }}.ovpn
    cat {{ ansible_env.HOME }}/openvpn-ca/keys/{{ item.client_name }}.key >> {{ ansible_env.HOME }}/client-configs/files/{{ item.client_name }}.ovpn
    echo  '</key>\n<tls-auth>' >> {{ ansible_env.HOME }}/client-configs/files/{{ item.client_name }}.ovpn
    cat {{ ansible_env.HOME }}/openvpn-ca/keys/ta.key >> {{ ansible_env.HOME }}/client-configs/files/{{ item.client_name }}.ovpn
    echo  '</tls-auth>' >> {{ ansible_env.HOME }}/client-configs/files/{{ item.client_name }}.ovpn
  loop: "{{ clients }}"
    

- name: "Fetch client configurations"
  fetch:
    src: "{{ ansible_env.HOME }}/client-configs/files/{{ item.client_name }}.ovpn"
    dest: keys/
    flat: yes
  loop: "{{ clients }}"
  